### ISSUE TITLE
pi-package-data conflicts with gnome-packagekit-data

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/pipackage#7]
With `pi-package-data` installed, trying to install `gnome-packagekit-data` fails.
```
dpkg: error processing archive /var/cache/apt/archives/gnome-packagekit-data_3.32.0-2_all.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/scalable/apps/gpk-log.svg', which is also in package pi-package-data 0.8
```
This breaks the installation of Snap Store.
I think this is a recent problem; I think that it began to occur recently on PiOS Bullseye and that it has not always been this way.

**Comment by spl237** [comment]
pi-package was forked from gnome-software in around 2015, and hasn't changed significantly since then, so it won't be a new problem. It looks like gnome have now renamed gnome-software to gnome-packagekit, in which case the Breaks lines in the control scripts will no longer prevent both being installed, which is probably what is causing the problem.

I'll update the Breaks / Conflicts lines in our control scripts. Very few people use this app anyway to my knowledge, so feel free to uninstall it if you prefer to use Gnome's version. Although I would expect them both to be using the same back end, so would expect that anything which can be installed with gnome-packagekit would also be installable with pi-package.

**Comment by spl237** [comment]
Yes, confirmed what is going on here.

Gnome used to have a software installer called gnome-software, which is what pi-package was forked from. They have now renamed gnome-software to gnome-packagekit, and created a completely different program which they have now put in the gnome-software package. Really helpful of them. Not.

I'll update our control file for pi-package accordingly - it now needs to not be installed with gnome-packagekit, not gnome-software.

**Comment by spl237** [comment]
In fact, it is even worse than that - gnome seem to have split gnome-software so that some of its files are now in gnome-software and some are in gnome-packagekit, so pi-package conflicts with both. I've added Conflicts entries for both to the pi-package package, so now installing either of the gnome- applications will uninstall pi-package.

**Comment by spl237** [comment]
Fixed version uploaded for bookworm.

**Comment by theofficialgman** [comment]
@spl237 you are very confused. let me help out.

`gnome-software` and `gnome-packagekit` are totally separate and have been for years (decades even). neither depend on one another and neither has changed. `gnome-software` is the store that everyone is familiar with.
`gnome-packagekit` is the software that nobody really uses that looks extremely similar to `pi-package` (because pi-package was forked from `gnome-packagekit`)

`gnome-software` has no conflicts or code dependence or conflicts with `pi-package` and `gnome-packagekit`.

`pi-package` and `gnome-packagekit` conflict with one another, yes, since they share some of the same attets as botspot mentioned here https://github.com/raspberrypi-ui/pipackage/issues/7#issue-1804058575

Please remove the `gnome-software` conflict as it is incorrect. The actual only conflict is between your `pi-package-session` package and the `packagekit` packge (yes those names are correct). `packagekit` IS a dependency of `gnome-software` but it isn't `gnome-software` itself that you conflict with.

If you want to correct that conflict it is simple. You should rename your `org.freedesktop.PackageKit.service` file to something else. that name is owned by `packagekit` and should not be used by your package unless you want to depend on the upstream `packagekit` package and not provide that functionality and those files yourself. That is the only file that conflicts.

**Comment by spl237** [comment]
Thank you for the input, but I am going to leave the conflicts as they are. Very few people use pi-package anyway, and I'm not inclined to spend any more time fixing it up. If people want to use gnome-software or gnome-packagekit they can, and either will now uninstall pi-package. I cannot think of any situation where people will want to have pi-package and either of the gnome installers installed at the same time given the overlap in their functionality.

**Comment by theofficialgman** [comment]
@spl237 is there any benefit of `pi-package` over upstream `gnome-packagekit`? maybe it is time to deprecate this repo and make the deb a transitional package back to `gnome-packagekit` if there is no benefit

**Comment by theofficialgman** [comment]
> I am going to leave the conflicts as they are

@spl237 yeah see that is the problem. you haven't fixed the issue with the conflicts as they are. you only account for if the user is ACTUALLY trying to install `gnome-software` or `gnome-packagekit`, both of which depend on `packagekit` (the actual conflict). Other things depend on `packagekit` and if the user tries to install one of them (just like @Botspot posed in the original issue) we are back to where we started with.

You need to use the actual package(s) that conflict, not just a small selection of a packages higher up that happen to depend on the conflicting package. So your conflicts should be `gnome-packagekit-data` and `packagekit` both of which have their own repective conflicting files `gpk-log.svg` and `org.freedesktop.PackageKit.service`. Commit https://github.com/raspberrypi-ui/pipackage/commit/20387a9c92f1c10d8d1fa29ca9761d098fb76eef does NOT solve this issue.
