### ISSUE TITLE
suggestion: deprecate and make `pi-package` and translational package to upstream `gnome-packagekit`

### ISSUE THREAD

**Issue by theofficialgman** [raspberrypi-ui/pipackage#9]
>  Yes, the look and feel of the GUI is nothing like anything else in Raspberry Pi OS so will stick out like a sore thumb...

@ghollingworth sorry have to open another issue since someone locked the convo https://github.com/raspberrypi-ui/pipackage/pull/8.
I am very annoyed that these PRs and issues keep getting closed and/or locked prematurely. that is not good product relations. I can see that you have never contributed to pipackage repo so I suggest you not make statements on no basis.

`pi-package` and `gnome-packagekit` look identical. we aren't talking about `gnome-software` as that is entirely different and as I have stated MANY times is NOT the same program. 

`pi-package`
![image](https://github.com/raspberrypi-ui/pipackage/assets/28281419/cd978c82-87c9-4391-8ca8-edaa1bbf5e9c)

`gnome-packagekit`
![image](https://github.com/raspberrypi-ui/pipackage/assets/28281419/2ae6856f-9602-43a0-a15d-d6421dc0ab4f)

they are identical (images pulled from debian official image repo and taken as a screenshot on rpi respectively).

So back to the original question:
Is there any benefit of `pi-package` over upstream `gnome-packagekit`? maybe it is time to deprecate this repo and make the deb a transitional package back to `gnome-packagekit` if there is no benefit. I respectfully ask that only @spl237 respond to this question as he is the only (public facing and referenced) developer of pipackage

**Comment by theofficialgman** [comment]
CC: @Botspot

**Comment by ghollingworth** [comment]
Were those two screenshots taken on the same Raspberry Pi with the same global GTK theme?

**Comment by theofficialgman** [comment]
> Were those two screenshots taken on the same Raspberry Pi with the same global GTK theme?

re-read what I wrote please. one was taken on a pi, the other was taken from the official debian images repository (see the watermark on the right side)
> they are identical (images pulled from debian official image repo and taken as a screenshot on rpi respectively).

**Comment by Botspot** [comment]
I just installed `gnome-packagekit` on PiOS and it looks exactly the same at first glance. It follows the system GTK theme and looks extremely similar to pi-package.
![image](https://github.com/raspberrypi-ui/pipackage/assets/54716352/25502e72-628c-46dd-b7a1-70dbc7ab7cce)

However, when installing a package or clicking on other UI elements, instead of a pop-up window displaying progress information, the base window itself a progress bar. It also completed operations faster and seemed more snappy than what I am used to from pi-package. I would say that this proposal to use upstream gnome-packagekit, while not very important compared to other issues, should receive a fair evaluation.

**Comment by spl237** [comment]
We will not be doing this, because the UX shortcomings of gnome-packagekit which were the reason we forked it originally have not improved in recent versions; in fact, the use of GNOME's new style with application controls on the title bar has made it even worse.
